[package]
name = "app-config"
version.workspace = true
edition.workspace = true

[dependencies]
config = "0.15.25"
dotenvy = "0.15"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-aux = "4.7.0"

[dependencies.sqlx]
version = "0.9.0"
features = ["postgres"]
