use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Tuma API",
        version = "0.1.0",
        description = "Backend API for the Tuma commerce + delivery platform"
    ),
    paths(
        crate::routes::health_check,
        crate::routes::openapi_json,
        crate::routes::me::me,
        crate::routes::me::update_me,
        crate::routes::auth::otp_request,
        crate::routes::auth::otp_verify,
        crate::routes::auth::login,
        crate::routes::auth::logout,
        crate::routes::auth::change_password,
        crate::routes::admin::create_merchant,
        crate::routes::admin::list_merchants,
        crate::routes::admin::get_merchant,
        crate::routes::admin::update_merchant,
        crate::routes::admin::delete_merchant,
        crate::routes::admin::list_customers,
        crate::routes::admin::update_customer,
        crate::routes::admin::delete_customer,
        crate::routes::admin::summary,
        crate::routes::stores::create_own_store,
        crate::routes::stores::list_own_stores,
        crate::routes::stores::get_own_store,
        crate::routes::stores::update_own_store,
        crate::routes::stores::delete_own_store,
        crate::routes::stores::list_stores,
        crate::routes::stores::get_store,
        crate::routes::search::search,
        crate::routes::catalog::create_product,
        crate::routes::catalog::list_products,
        crate::routes::catalog::update_product,
        crate::routes::catalog::delete_product,
        crate::routes::catalog::create_store_product,
        crate::routes::catalog::list_store_products,
        crate::routes::catalog::update_store_product,
        crate::routes::catalog::delete_store_product,
        crate::routes::orders::checkout,
        crate::routes::orders::list_orders,
        crate::routes::orders::get_order,
        crate::routes::orders::cancel_store_order,
        crate::routes::orders::list_merchant_orders,
        crate::routes::orders::get_merchant_store_order,
        crate::routes::orders::advance_store_order,
        crate::routes::storage::upload_store_banner,
        crate::routes::storage::delete_store_banner,
        crate::routes::storage::list_product_images,
        crate::routes::storage::upload_product_image,
        crate::routes::storage::delete_product_image,
        crate::routes::storage::set_product_cover,
        crate::routes::files::get_file,
    )
)]
pub struct ApiDoc;
