/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminRidersRouteImport } from './routes/admin/riders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantCatalogRouteImport } from './routes/merchant/catalog'
import { Route as MerchantEarningsRouteImport } from './routes/merchant/earnings'
import { Route as MerchantMenuRouteImport } from './routes/merchant/menu'
import { Route as MerchantOrdersRouteImport } from './routes/merchant/orders'
import { Route as MerchantReviewsRouteImport } from './routes/merchant/reviews'
import { Route as MerchantSettingsRouteImport } from './routes/merchant/settings'
import { Route as AdminDisputesDisputeIdRouteImport } from './routes/admin/disputes.$disputeId'
import { Route as AdminMerchantsIndexRouteImport } from './routes/admin/merchants.index'
import { Route as AdminMerchantsMerchantIdRouteImport } from './routes/admin/merchants.$merchantId'
import { Route as AdminMerchantsNewRouteImport } from './routes/admin/merchants.new'
import { Route as AdminRidersNewRouteImport } from './routes/admin/riders.new'
import { Route as MerchantCatalogProductIdRouteImport } from './routes/merchant/catalog.$productId'
import { Route as MerchantCatalogNewRouteImport } from './routes/merchant/catalog.new'
import { Route as MerchantMenuProductIdRouteImport } from './routes/merchant/menu.$productId'
import { Route as MerchantMenuNewRouteImport } from './routes/merchant/menu.new'
import { Route as MerchantStoreIndexRouteImport } from './routes/merchant/store.index'
import { Route as MerchantStoreStoreIdRouteImport } from './routes/merchant/store.$storeId'
import { Route as MerchantStoreNewRouteImport } from './routes/merchant/store.new'
import { Route as AdminMerchantsMerchantIdEditRouteImport } from './routes/admin/merchants.$merchantId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantCatalogRoute = MerchantCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantEarningsRoute = MerchantEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantReviewsRoute = MerchantReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const AdminDisputesDisputeIdRoute = AdminDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMerchantsMerchantIdRoute =
  AdminMerchantsMerchantIdRouteImport.update({
    id: '/merchants/$merchantId',
    path: '/merchants/$merchantId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMerchantsNewRoute = AdminMerchantsNewRouteImport.update({
  id: '/merchants/new',
  path: '/merchants/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidersNewRoute = AdminRidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRidersRoute,
} as any)
const MerchantCatalogProductIdRoute =
  MerchantCatalogProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => MerchantCatalogRoute,
  } as any)
const MerchantCatalogNewRoute = MerchantCatalogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantCatalogRoute,
} as any)
const MerchantMenuProductIdRoute = MerchantMenuProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MerchantMenuRoute,
} as any)
const MerchantMenuNewRoute = MerchantMenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantMenuRoute,
} as any)
const MerchantStoreIndexRoute = MerchantStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantStoreStoreIdRoute = MerchantStoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantStoreNewRoute = MerchantStoreNewRouteImport.update({
  id: '/store/new',
  path: '/store/new',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const AdminMerchantsMerchantIdEditRoute =
  AdminMerchantsMerchantIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminMerchantsMerchantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/fees': typeof AdminFeesRoute
  '/admin/riders': typeof AdminRidersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/catalog': typeof MerchantCatalogRouteWithChildren
  '/merchant/earnings': typeof MerchantEarningsRoute
  '/merchant/menu': typeof MerchantMenuRouteWithChildren
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/fees': typeof AdminFeesRoute
  '/admin/riders': typeof AdminRidersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/catalog': typeof MerchantCatalogRouteWithChildren
  '/merchant/earnings': typeof MerchantEarningsRoute
  '/merchant/menu': typeof MerchantMenuRouteWithChildren
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/merchants': typeof AdminMerchantsIndexRoute
  '/merchant/store': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/fees': typeof AdminFeesRoute
  '/admin/riders': typeof AdminRidersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/catalog': typeof MerchantCatalogRouteWithChildren
  '/merchant/earnings': typeof MerchantEarningsRoute
  '/merchant/menu': typeof MerchantMenuRouteWithChildren
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/fees'
    | '/admin/riders'
    | '/admin/settings'
    | '/merchant/catalog'
    | '/merchant/earnings'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/admin/'
    | '/merchant/'
    | '/admin/disputes/$disputeId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/merchants/'
    | '/merchant/store/'
    | '/admin/merchants/$merchantId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/fees'
    | '/admin/riders'
    | '/admin/settings'
    | '/merchant/catalog'
    | '/merchant/earnings'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/admin'
    | '/merchant'
    | '/admin/disputes/$disputeId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/merchants'
    | '/merchant/store'
    | '/admin/merchants/$merchantId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/fees'
    | '/admin/riders'
    | '/admin/settings'
    | '/merchant/catalog'
    | '/merchant/earnings'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/admin/'
    | '/merchant/'
    | '/admin/disputes/$disputeId'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/merchants/'
    | '/merchant/store/'
    | '/admin/merchants/$merchantId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/catalog': {
      id: '/merchant/catalog'
      path: '/catalog'
      fullPath: '/merchant/catalog'
      preLoaderRoute: typeof MerchantCatalogRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/earnings': {
      id: '/merchant/earnings'
      path: '/earnings'
      fullPath: '/merchant/earnings'
      preLoaderRoute: typeof MerchantEarningsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/reviews': {
      id: '/merchant/reviews'
      path: '/reviews'
      fullPath: '/merchant/reviews'
      preLoaderRoute: typeof MerchantReviewsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/admin/disputes/$disputeId': {
      id: '/admin/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/admin/disputes/$disputeId'
      preLoaderRoute: typeof AdminDisputesDisputeIdRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/admin/merchants/': {
      id: '/admin/merchants/'
      path: '/merchants'
      fullPath: '/admin/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants/$merchantId': {
      id: '/admin/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/admin/merchants/$merchantId'
      preLoaderRoute: typeof AdminMerchantsMerchantIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants/new': {
      id: '/admin/merchants/new'
      path: '/merchants/new'
      fullPath: '/admin/merchants/new'
      preLoaderRoute: typeof AdminMerchantsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/riders/new': {
      id: '/admin/riders/new'
      path: '/new'
      fullPath: '/admin/riders/new'
      preLoaderRoute: typeof AdminRidersNewRouteImport
      parentRoute: typeof AdminRidersRoute
    }
    '/merchant/catalog/$productId': {
      id: '/merchant/catalog/$productId'
      path: '/$productId'
      fullPath: '/merchant/catalog/$productId'
      preLoaderRoute: typeof MerchantCatalogProductIdRouteImport
      parentRoute: typeof MerchantCatalogRoute
    }
    '/merchant/catalog/new': {
      id: '/merchant/catalog/new'
      path: '/new'
      fullPath: '/merchant/catalog/new'
      preLoaderRoute: typeof MerchantCatalogNewRouteImport
      parentRoute: typeof MerchantCatalogRoute
    }
    '/merchant/menu/$productId': {
      id: '/merchant/menu/$productId'
      path: '/$productId'
      fullPath: '/merchant/menu/$productId'
      preLoaderRoute: typeof MerchantMenuProductIdRouteImport
      parentRoute: typeof MerchantMenuRoute
    }
    '/merchant/menu/new': {
      id: '/merchant/menu/new'
      path: '/new'
      fullPath: '/merchant/menu/new'
      preLoaderRoute: typeof MerchantMenuNewRouteImport
      parentRoute: typeof MerchantMenuRoute
    }
    '/merchant/store/': {
      id: '/merchant/store/'
      path: '/store'
      fullPath: '/merchant/store/'
      preLoaderRoute: typeof MerchantStoreIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/store/$storeId': {
      id: '/merchant/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/merchant/store/$storeId'
      preLoaderRoute: typeof MerchantStoreStoreIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/store/new': {
      id: '/merchant/store/new'
      path: '/store/new'
      fullPath: '/merchant/store/new'
      preLoaderRoute: typeof MerchantStoreNewRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/admin/merchants/$merchantId/edit': {
      id: '/admin/merchants/$merchantId/edit'
      path: '/edit'
      fullPath: '/admin/merchants/$merchantId/edit'
      preLoaderRoute: typeof AdminMerchantsMerchantIdEditRouteImport
      parentRoute: typeof AdminMerchantsMerchantIdRoute
    }
  }
}

interface AdminDisputesRouteChildren {
  AdminDisputesDisputeIdRoute: typeof AdminDisputesDisputeIdRoute
}

const AdminDisputesRouteChildren: AdminDisputesRouteChildren = {
  AdminDisputesDisputeIdRoute: AdminDisputesDisputeIdRoute,
}

const AdminDisputesRouteWithChildren = AdminDisputesRoute._addFileChildren(
  AdminDisputesRouteChildren,
)

interface AdminRidersRouteChildren {
  AdminRidersNewRoute: typeof AdminRidersNewRoute
}

const AdminRidersRouteChildren: AdminRidersRouteChildren = {
  AdminRidersNewRoute: AdminRidersNewRoute,
}

const AdminRidersRouteWithChildren = AdminRidersRoute._addFileChildren(
  AdminRidersRouteChildren,
)

interface AdminMerchantsMerchantIdRouteChildren {
  AdminMerchantsMerchantIdEditRoute: typeof AdminMerchantsMerchantIdEditRoute
}

const AdminMerchantsMerchantIdRouteChildren: AdminMerchantsMerchantIdRouteChildren =
  {
    AdminMerchantsMerchantIdEditRoute: AdminMerchantsMerchantIdEditRoute,
  }

const AdminMerchantsMerchantIdRouteWithChildren =
  AdminMerchantsMerchantIdRoute._addFileChildren(
    AdminMerchantsMerchantIdRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDisputesRoute: typeof AdminDisputesRouteWithChildren
  AdminFeesRoute: typeof AdminFeesRoute
  AdminRidersRoute: typeof AdminRidersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMerchantsMerchantIdRoute: typeof AdminMerchantsMerchantIdRouteWithChildren
  AdminMerchantsNewRoute: typeof AdminMerchantsNewRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDisputesRoute: AdminDisputesRouteWithChildren,
  AdminFeesRoute: AdminFeesRoute,
  AdminRidersRoute: AdminRidersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMerchantsMerchantIdRoute: AdminMerchantsMerchantIdRouteWithChildren,
  AdminMerchantsNewRoute: AdminMerchantsNewRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MerchantCatalogRouteChildren {
  MerchantCatalogProductIdRoute: typeof MerchantCatalogProductIdRoute
  MerchantCatalogNewRoute: typeof MerchantCatalogNewRoute
}

const MerchantCatalogRouteChildren: MerchantCatalogRouteChildren = {
  MerchantCatalogProductIdRoute: MerchantCatalogProductIdRoute,
  MerchantCatalogNewRoute: MerchantCatalogNewRoute,
}

const MerchantCatalogRouteWithChildren = MerchantCatalogRoute._addFileChildren(
  MerchantCatalogRouteChildren,
)

interface MerchantMenuRouteChildren {
  MerchantMenuProductIdRoute: typeof MerchantMenuProductIdRoute
  MerchantMenuNewRoute: typeof MerchantMenuNewRoute
}

const MerchantMenuRouteChildren: MerchantMenuRouteChildren = {
  MerchantMenuProductIdRoute: MerchantMenuProductIdRoute,
  MerchantMenuNewRoute: MerchantMenuNewRoute,
}

const MerchantMenuRouteWithChildren = MerchantMenuRoute._addFileChildren(
  MerchantMenuRouteChildren,
)

interface MerchantRouteRouteChildren {
  MerchantCatalogRoute: typeof MerchantCatalogRouteWithChildren
  MerchantEarningsRoute: typeof MerchantEarningsRoute
  MerchantMenuRoute: typeof MerchantMenuRouteWithChildren
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantReviewsRoute: typeof MerchantReviewsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantStoreStoreIdRoute: typeof MerchantStoreStoreIdRoute
  MerchantStoreNewRoute: typeof MerchantStoreNewRoute
  MerchantStoreIndexRoute: typeof MerchantStoreIndexRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantCatalogRoute: MerchantCatalogRouteWithChildren,
  MerchantEarningsRoute: MerchantEarningsRoute,
  MerchantMenuRoute: MerchantMenuRouteWithChildren,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantReviewsRoute: MerchantReviewsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantStoreStoreIdRoute: MerchantStoreStoreIdRoute,
  MerchantStoreNewRoute: MerchantStoreNewRoute,
  MerchantStoreIndexRoute: MerchantStoreIndexRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
