/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminMerchantsRouteRouteImport } from './routes/admin/merchants/route'
import { Route as AdminRidersRouteRouteImport } from './routes/admin/riders/route'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantCatalogRouteRouteImport } from './routes/merchant/catalog/route'
import { Route as MerchantMenuRouteRouteImport } from './routes/merchant/menu/route'
import { Route as MerchantStoreRouteRouteImport } from './routes/merchant/store/route'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminMerchantsIndexRouteImport } from './routes/admin/merchants/index'
import { Route as AdminMerchantsMerchantIdRouteRouteImport } from './routes/admin/merchants/$merchantId/route'
import { Route as AdminMerchantsNewRouteImport } from './routes/admin/merchants/new'
import { Route as AdminRidersIndexRouteImport } from './routes/admin/riders/index'
import { Route as AdminRidersNewRouteImport } from './routes/admin/riders/new'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as MerchantCatalogIndexRouteImport } from './routes/merchant/catalog/index'
import { Route as MerchantCatalogProductIdRouteImport } from './routes/merchant/catalog/$productId'
import { Route as MerchantCatalogNewRouteImport } from './routes/merchant/catalog/new'
import { Route as MerchantMenuIndexRouteImport } from './routes/merchant/menu/index'
import { Route as MerchantMenuProductIdRouteImport } from './routes/merchant/menu/$productId'
import { Route as MerchantMenuNewRouteImport } from './routes/merchant/menu/new'
import { Route as MerchantOrdersIndexRouteImport } from './routes/merchant/orders/index'
import { Route as MerchantSettingsIndexRouteImport } from './routes/merchant/settings/index'
import { Route as MerchantStoreIndexRouteImport } from './routes/merchant/store/index'
import { Route as MerchantStoreStoreIdRouteImport } from './routes/merchant/store/$storeId'
import { Route as MerchantStoreNewRouteImport } from './routes/merchant/store/new'
import { Route as AdminMerchantsMerchantIdIndexRouteImport } from './routes/admin/merchants/$merchantId/index'
import { Route as AdminMerchantsMerchantIdEditRouteImport } from './routes/admin/merchants/$merchantId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMerchantsRouteRoute = AdminMerchantsRouteRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidersRouteRoute = AdminRidersRouteRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantCatalogRouteRoute = MerchantCatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantMenuRouteRoute = MerchantMenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantStoreRouteRoute = MerchantStoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMerchantsRouteRoute,
} as any)
const AdminMerchantsMerchantIdRouteRoute =
  AdminMerchantsMerchantIdRouteRouteImport.update({
    id: '/$merchantId',
    path: '/$merchantId',
    getParentRoute: () => AdminMerchantsRouteRoute,
  } as any)
const AdminMerchantsNewRoute = AdminMerchantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMerchantsRouteRoute,
} as any)
const AdminRidersIndexRoute = AdminRidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRidersRouteRoute,
} as any)
const AdminRidersNewRoute = AdminRidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRidersRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MerchantCatalogIndexRoute = MerchantCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantCatalogRouteRoute,
} as any)
const MerchantCatalogProductIdRoute =
  MerchantCatalogProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => MerchantCatalogRouteRoute,
  } as any)
const MerchantCatalogNewRoute = MerchantCatalogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantCatalogRouteRoute,
} as any)
const MerchantMenuIndexRoute = MerchantMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantMenuRouteRoute,
} as any)
const MerchantMenuProductIdRoute = MerchantMenuProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MerchantMenuRouteRoute,
} as any)
const MerchantMenuNewRoute = MerchantMenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantMenuRouteRoute,
} as any)
const MerchantOrdersIndexRoute = MerchantOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantSettingsIndexRoute = MerchantSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantStoreIndexRoute = MerchantStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantStoreRouteRoute,
} as any)
const MerchantStoreStoreIdRoute = MerchantStoreStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => MerchantStoreRouteRoute,
} as any)
const MerchantStoreNewRoute = MerchantStoreNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MerchantStoreRouteRoute,
} as any)
const AdminMerchantsMerchantIdIndexRoute =
  AdminMerchantsMerchantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMerchantsMerchantIdRouteRoute,
  } as any)
const AdminMerchantsMerchantIdEditRoute =
  AdminMerchantsMerchantIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminMerchantsMerchantIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/merchants': typeof AdminMerchantsRouteRouteWithChildren
  '/admin/riders': typeof AdminRidersRouteRouteWithChildren
  '/merchant/catalog': typeof MerchantCatalogRouteRouteWithChildren
  '/merchant/menu': typeof MerchantMenuRouteRouteWithChildren
  '/merchant/store': typeof MerchantStoreRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/riders/': typeof AdminRidersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/merchant/catalog/': typeof MerchantCatalogIndexRoute
  '/merchant/menu/': typeof MerchantMenuIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
  '/admin/merchants/$merchantId/': typeof AdminMerchantsMerchantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/merchants': typeof AdminMerchantsIndexRoute
  '/admin/riders': typeof AdminRidersIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/merchant/catalog': typeof MerchantCatalogIndexRoute
  '/merchant/menu': typeof MerchantMenuIndexRoute
  '/merchant/orders': typeof MerchantOrdersIndexRoute
  '/merchant/settings': typeof MerchantSettingsIndexRoute
  '/merchant/store': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/merchants': typeof AdminMerchantsRouteRouteWithChildren
  '/admin/riders': typeof AdminRidersRouteRouteWithChildren
  '/merchant/catalog': typeof MerchantCatalogRouteRouteWithChildren
  '/merchant/menu': typeof MerchantMenuRouteRouteWithChildren
  '/merchant/store': typeof MerchantStoreRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRouteRouteWithChildren
  '/admin/merchants/new': typeof AdminMerchantsNewRoute
  '/admin/riders/new': typeof AdminRidersNewRoute
  '/merchant/catalog/$productId': typeof MerchantCatalogProductIdRoute
  '/merchant/catalog/new': typeof MerchantCatalogNewRoute
  '/merchant/menu/$productId': typeof MerchantMenuProductIdRoute
  '/merchant/menu/new': typeof MerchantMenuNewRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/merchant/store/new': typeof MerchantStoreNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/riders/': typeof AdminRidersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/merchant/catalog/': typeof MerchantCatalogIndexRoute
  '/merchant/menu/': typeof MerchantMenuIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
  '/admin/merchants/$merchantId/edit': typeof AdminMerchantsMerchantIdEditRoute
  '/admin/merchants/$merchantId/': typeof AdminMerchantsMerchantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/merchants'
    | '/admin/riders'
    | '/merchant/catalog'
    | '/merchant/menu'
    | '/merchant/store'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/customers/'
    | '/admin/merchants/'
    | '/admin/riders/'
    | '/admin/settings/'
    | '/merchant/catalog/'
    | '/merchant/menu/'
    | '/merchant/orders/'
    | '/merchant/settings/'
    | '/merchant/store/'
    | '/admin/merchants/$merchantId/edit'
    | '/admin/merchants/$merchantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/merchant'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/customers'
    | '/admin/merchants'
    | '/admin/riders'
    | '/admin/settings'
    | '/merchant/catalog'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/settings'
    | '/merchant/store'
    | '/admin/merchants/$merchantId/edit'
    | '/admin/merchants/$merchantId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/merchants'
    | '/admin/riders'
    | '/merchant/catalog'
    | '/merchant/menu'
    | '/merchant/store'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$merchantId'
    | '/admin/merchants/new'
    | '/admin/riders/new'
    | '/merchant/catalog/$productId'
    | '/merchant/catalog/new'
    | '/merchant/menu/$productId'
    | '/merchant/menu/new'
    | '/merchant/store/$storeId'
    | '/merchant/store/new'
    | '/admin/customers/'
    | '/admin/merchants/'
    | '/admin/riders/'
    | '/admin/settings/'
    | '/merchant/catalog/'
    | '/merchant/menu/'
    | '/merchant/orders/'
    | '/merchant/settings/'
    | '/merchant/store/'
    | '/admin/merchants/$merchantId/edit'
    | '/admin/merchants/$merchantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/catalog': {
      id: '/merchant/catalog'
      path: '/catalog'
      fullPath: '/merchant/catalog'
      preLoaderRoute: typeof MerchantCatalogRouteRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/store': {
      id: '/merchant/store'
      path: '/store'
      fullPath: '/merchant/store'
      preLoaderRoute: typeof MerchantStoreRouteRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants/': {
      id: '/admin/merchants/'
      path: '/'
      fullPath: '/admin/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof AdminMerchantsRouteRoute
    }
    '/admin/merchants/$merchantId': {
      id: '/admin/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/admin/merchants/$merchantId'
      preLoaderRoute: typeof AdminMerchantsMerchantIdRouteRouteImport
      parentRoute: typeof AdminMerchantsRouteRoute
    }
    '/admin/merchants/new': {
      id: '/admin/merchants/new'
      path: '/new'
      fullPath: '/admin/merchants/new'
      preLoaderRoute: typeof AdminMerchantsNewRouteImport
      parentRoute: typeof AdminMerchantsRouteRoute
    }
    '/admin/riders/': {
      id: '/admin/riders/'
      path: '/'
      fullPath: '/admin/riders/'
      preLoaderRoute: typeof AdminRidersIndexRouteImport
      parentRoute: typeof AdminRidersRouteRoute
    }
    '/admin/riders/new': {
      id: '/admin/riders/new'
      path: '/new'
      fullPath: '/admin/riders/new'
      preLoaderRoute: typeof AdminRidersNewRouteImport
      parentRoute: typeof AdminRidersRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/catalog/': {
      id: '/merchant/catalog/'
      path: '/'
      fullPath: '/merchant/catalog/'
      preLoaderRoute: typeof MerchantCatalogIndexRouteImport
      parentRoute: typeof MerchantCatalogRouteRoute
    }
    '/merchant/catalog/$productId': {
      id: '/merchant/catalog/$productId'
      path: '/$productId'
      fullPath: '/merchant/catalog/$productId'
      preLoaderRoute: typeof MerchantCatalogProductIdRouteImport
      parentRoute: typeof MerchantCatalogRouteRoute
    }
    '/merchant/catalog/new': {
      id: '/merchant/catalog/new'
      path: '/new'
      fullPath: '/merchant/catalog/new'
      preLoaderRoute: typeof MerchantCatalogNewRouteImport
      parentRoute: typeof MerchantCatalogRouteRoute
    }
    '/merchant/menu/': {
      id: '/merchant/menu/'
      path: '/'
      fullPath: '/merchant/menu/'
      preLoaderRoute: typeof MerchantMenuIndexRouteImport
      parentRoute: typeof MerchantMenuRouteRoute
    }
    '/merchant/menu/$productId': {
      id: '/merchant/menu/$productId'
      path: '/$productId'
      fullPath: '/merchant/menu/$productId'
      preLoaderRoute: typeof MerchantMenuProductIdRouteImport
      parentRoute: typeof MerchantMenuRouteRoute
    }
    '/merchant/menu/new': {
      id: '/merchant/menu/new'
      path: '/new'
      fullPath: '/merchant/menu/new'
      preLoaderRoute: typeof MerchantMenuNewRouteImport
      parentRoute: typeof MerchantMenuRouteRoute
    }
    '/merchant/orders/': {
      id: '/merchant/orders/'
      path: '/orders'
      fullPath: '/merchant/orders/'
      preLoaderRoute: typeof MerchantOrdersIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/settings/': {
      id: '/merchant/settings/'
      path: '/settings'
      fullPath: '/merchant/settings/'
      preLoaderRoute: typeof MerchantSettingsIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/store/': {
      id: '/merchant/store/'
      path: '/'
      fullPath: '/merchant/store/'
      preLoaderRoute: typeof MerchantStoreIndexRouteImport
      parentRoute: typeof MerchantStoreRouteRoute
    }
    '/merchant/store/$storeId': {
      id: '/merchant/store/$storeId'
      path: '/$storeId'
      fullPath: '/merchant/store/$storeId'
      preLoaderRoute: typeof MerchantStoreStoreIdRouteImport
      parentRoute: typeof MerchantStoreRouteRoute
    }
    '/merchant/store/new': {
      id: '/merchant/store/new'
      path: '/new'
      fullPath: '/merchant/store/new'
      preLoaderRoute: typeof MerchantStoreNewRouteImport
      parentRoute: typeof MerchantStoreRouteRoute
    }
    '/admin/merchants/$merchantId/': {
      id: '/admin/merchants/$merchantId/'
      path: '/'
      fullPath: '/admin/merchants/$merchantId/'
      preLoaderRoute: typeof AdminMerchantsMerchantIdIndexRouteImport
      parentRoute: typeof AdminMerchantsMerchantIdRouteRoute
    }
    '/admin/merchants/$merchantId/edit': {
      id: '/admin/merchants/$merchantId/edit'
      path: '/edit'
      fullPath: '/admin/merchants/$merchantId/edit'
      preLoaderRoute: typeof AdminMerchantsMerchantIdEditRouteImport
      parentRoute: typeof AdminMerchantsMerchantIdRouteRoute
    }
  }
}

interface AdminMerchantsMerchantIdRouteRouteChildren {
  AdminMerchantsMerchantIdEditRoute: typeof AdminMerchantsMerchantIdEditRoute
  AdminMerchantsMerchantIdIndexRoute: typeof AdminMerchantsMerchantIdIndexRoute
}

const AdminMerchantsMerchantIdRouteRouteChildren: AdminMerchantsMerchantIdRouteRouteChildren =
  {
    AdminMerchantsMerchantIdEditRoute: AdminMerchantsMerchantIdEditRoute,
    AdminMerchantsMerchantIdIndexRoute: AdminMerchantsMerchantIdIndexRoute,
  }

const AdminMerchantsMerchantIdRouteRouteWithChildren =
  AdminMerchantsMerchantIdRouteRoute._addFileChildren(
    AdminMerchantsMerchantIdRouteRouteChildren,
  )

interface AdminMerchantsRouteRouteChildren {
  AdminMerchantsMerchantIdRouteRoute: typeof AdminMerchantsMerchantIdRouteRouteWithChildren
  AdminMerchantsNewRoute: typeof AdminMerchantsNewRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
}

const AdminMerchantsRouteRouteChildren: AdminMerchantsRouteRouteChildren = {
  AdminMerchantsMerchantIdRouteRoute:
    AdminMerchantsMerchantIdRouteRouteWithChildren,
  AdminMerchantsNewRoute: AdminMerchantsNewRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
}

const AdminMerchantsRouteRouteWithChildren =
  AdminMerchantsRouteRoute._addFileChildren(AdminMerchantsRouteRouteChildren)

interface AdminRidersRouteRouteChildren {
  AdminRidersNewRoute: typeof AdminRidersNewRoute
  AdminRidersIndexRoute: typeof AdminRidersIndexRoute
}

const AdminRidersRouteRouteChildren: AdminRidersRouteRouteChildren = {
  AdminRidersNewRoute: AdminRidersNewRoute,
  AdminRidersIndexRoute: AdminRidersIndexRoute,
}

const AdminRidersRouteRouteWithChildren =
  AdminRidersRouteRoute._addFileChildren(AdminRidersRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminMerchantsRouteRoute: typeof AdminMerchantsRouteRouteWithChildren
  AdminRidersRouteRoute: typeof AdminRidersRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMerchantsRouteRoute: AdminMerchantsRouteRouteWithChildren,
  AdminRidersRouteRoute: AdminRidersRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MerchantCatalogRouteRouteChildren {
  MerchantCatalogProductIdRoute: typeof MerchantCatalogProductIdRoute
  MerchantCatalogNewRoute: typeof MerchantCatalogNewRoute
  MerchantCatalogIndexRoute: typeof MerchantCatalogIndexRoute
}

const MerchantCatalogRouteRouteChildren: MerchantCatalogRouteRouteChildren = {
  MerchantCatalogProductIdRoute: MerchantCatalogProductIdRoute,
  MerchantCatalogNewRoute: MerchantCatalogNewRoute,
  MerchantCatalogIndexRoute: MerchantCatalogIndexRoute,
}

const MerchantCatalogRouteRouteWithChildren =
  MerchantCatalogRouteRoute._addFileChildren(MerchantCatalogRouteRouteChildren)

interface MerchantMenuRouteRouteChildren {
  MerchantMenuProductIdRoute: typeof MerchantMenuProductIdRoute
  MerchantMenuNewRoute: typeof MerchantMenuNewRoute
  MerchantMenuIndexRoute: typeof MerchantMenuIndexRoute
}

const MerchantMenuRouteRouteChildren: MerchantMenuRouteRouteChildren = {
  MerchantMenuProductIdRoute: MerchantMenuProductIdRoute,
  MerchantMenuNewRoute: MerchantMenuNewRoute,
  MerchantMenuIndexRoute: MerchantMenuIndexRoute,
}

const MerchantMenuRouteRouteWithChildren =
  MerchantMenuRouteRoute._addFileChildren(MerchantMenuRouteRouteChildren)

interface MerchantStoreRouteRouteChildren {
  MerchantStoreStoreIdRoute: typeof MerchantStoreStoreIdRoute
  MerchantStoreNewRoute: typeof MerchantStoreNewRoute
  MerchantStoreIndexRoute: typeof MerchantStoreIndexRoute
}

const MerchantStoreRouteRouteChildren: MerchantStoreRouteRouteChildren = {
  MerchantStoreStoreIdRoute: MerchantStoreStoreIdRoute,
  MerchantStoreNewRoute: MerchantStoreNewRoute,
  MerchantStoreIndexRoute: MerchantStoreIndexRoute,
}

const MerchantStoreRouteRouteWithChildren =
  MerchantStoreRouteRoute._addFileChildren(MerchantStoreRouteRouteChildren)

interface MerchantRouteRouteChildren {
  MerchantCatalogRouteRoute: typeof MerchantCatalogRouteRouteWithChildren
  MerchantMenuRouteRoute: typeof MerchantMenuRouteRouteWithChildren
  MerchantStoreRouteRoute: typeof MerchantStoreRouteRouteWithChildren
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantOrdersIndexRoute: typeof MerchantOrdersIndexRoute
  MerchantSettingsIndexRoute: typeof MerchantSettingsIndexRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantCatalogRouteRoute: MerchantCatalogRouteRouteWithChildren,
  MerchantMenuRouteRoute: MerchantMenuRouteRouteWithChildren,
  MerchantStoreRouteRoute: MerchantStoreRouteRouteWithChildren,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantOrdersIndexRoute: MerchantOrdersIndexRoute,
  MerchantSettingsIndexRoute: MerchantSettingsIndexRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
