/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantDashboardRouteImport } from './routes/merchant/dashboard'
import { Route as MerchantMenuRouteImport } from './routes/merchant/menu'
import { Route as MerchantSettingsRouteImport } from './routes/merchant/settings'
import { Route as AdminMerchantsIndexRouteImport } from './routes/admin/merchants/index'
import { Route as AdminMerchantsMerchantIdRouteImport } from './routes/admin/merchants/$merchantId'
import { Route as MerchantStoreIndexRouteImport } from './routes/merchant/store/index'
import { Route as MerchantStoreStoreIdRouteImport } from './routes/merchant/store/$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMerchantsMerchantIdRoute =
  AdminMerchantsMerchantIdRouteImport.update({
    id: '/merchants/$merchantId',
    path: '/merchants/$merchantId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const MerchantStoreIndexRoute = MerchantStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantStoreStoreIdRoute = MerchantStoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => MerchantRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/admin/merchants': typeof AdminMerchantsIndexRoute
  '/merchant/store': typeof MerchantStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$merchantId': typeof AdminMerchantsMerchantIdRoute
  '/merchant/store/$storeId': typeof MerchantStoreStoreIdRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/merchant/store/': typeof MerchantStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/merchant/dashboard'
    | '/merchant/menu'
    | '/merchant/settings'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$merchantId'
    | '/merchant/store/$storeId'
    | '/admin/merchants/'
    | '/merchant/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/merchant/dashboard'
    | '/merchant/menu'
    | '/merchant/settings'
    | '/admin'
    | '/merchant'
    | '/admin/merchants/$merchantId'
    | '/merchant/store/$storeId'
    | '/admin/merchants'
    | '/merchant/store'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/merchant'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/merchant/dashboard'
    | '/merchant/menu'
    | '/merchant/settings'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$merchantId'
    | '/merchant/store/$storeId'
    | '/admin/merchants/'
    | '/merchant/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/admin/merchants/': {
      id: '/admin/merchants/'
      path: '/merchants'
      fullPath: '/admin/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants/$merchantId': {
      id: '/admin/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/admin/merchants/$merchantId'
      preLoaderRoute: typeof AdminMerchantsMerchantIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/store/': {
      id: '/merchant/store/'
      path: '/store'
      fullPath: '/merchant/store/'
      preLoaderRoute: typeof MerchantStoreIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/store/$storeId': {
      id: '/merchant/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/merchant/store/$storeId'
      preLoaderRoute: typeof MerchantStoreStoreIdRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMerchantsMerchantIdRoute: typeof AdminMerchantsMerchantIdRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMerchantsMerchantIdRoute: AdminMerchantsMerchantIdRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MerchantRouteRouteChildren {
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantStoreStoreIdRoute: typeof MerchantStoreStoreIdRoute
  MerchantStoreIndexRoute: typeof MerchantStoreIndexRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantStoreStoreIdRoute: MerchantStoreStoreIdRoute,
  MerchantStoreIndexRoute: MerchantStoreIndexRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
